#!/usr/bin/env bash
# Description: Generate and set a random hostname on Linux, that imitates a MacBook's hostname
# Usage: set-random-hostname

__set_random_hostname() {

  # set a prefix if you'd like (thx for the idea @czerniachowicz)
  new_hostname="$(shuf -n 1 /usr/share/first-names.txt)-MacBook-Pro"  
  # ensure new hostname is not too long
  if [ ${#new_hostname} -gt 63 ]; then
    new_hostname=${new_hostname:0:63}
  fi

  # set new hostname
  hostnamectl set-hostname "$new_hostname"
  sed -i "/^127\.0\.1\.1\s/c\127.0.1.1       $new_hostname" /etc/hosts

}

__set_random_hostname
